EPOCH_MS_DEFAULT = 1288834974657
NODE_ID_DEFAULT = 1

TIMESTAMP_BITS = 41
NODE_ID_BITS = 10
SEQUENCE_ID_BITS = 12

TIMESTAMP_MS_MAX = (1 << TIMESTAMP_BITS) - 1
NODE_ID_MAX = (1 << NODE_ID_BITS) - 1
SEQUENCE_ID_MAX = (1 << SEQUENCE_ID_BITS) - 1

NODE_ID_SHIFT = SEQUENCE_ID_BITS
TIMESTAMP_SHIFT = SEQUENCE_ID_BITS + NODE_ID_BITS